#---------------------------------------------------------------------

# This file was generated by ../programming/imageinsource/Image2PyFile.py

from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
#---------------------------------------------------------------------

antenna32_32_ico = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABcdJ"
    "REFUWIW9l0tIVF8cxz/n3KsmiTqDr5lSERkwxwmmMi0rghJyoQVDNm0KV61bVOvWbdoFkfuZ"
    "BokiaFPRwoJsMlGHUFLGBzo2xgyBjxnvvfNf9L+Xefiq/+MLFw7n/M7v972/1zlHbG1tZchD"
    "JpNBCJE//Y+wk051O0EpJQCrq6usra2xsbFBJlPAc1cIISgtLeXgwYNUVVUhhMAwjAISOQQy"
    "mQxFRUXEYjGGh4f58uULS0tLrK6u/hGBqqoqnE4nXq+XM2fOUFdXx9bWVg4JkU6nM6bx4uJi"
    "Pn/+TCAQYGZmBl3X0TTtt41nk1BVFUVRaG5uxu/3c/z4cdLptEXC8oCqqiwsLDA4OEg8HkdK"
    "ybFjx+jp6aG+vh5FUX7LuK7rLCws8OrVK8bGxohGowwODlJTU8OhQ4fQdf0XSTMJVVXlwYMH"
    "fPr0CSklV69exefzWQp/JzHzZYeGhgiFQhiGQXt7O3fu3EHTNACkmXRTU1PMzc2h6zperxef"
    "z0cmk7Hc/ztVYcqa+30+H16vF13XmZubY2pqCinlr4Q3N8ViMZLJJJqm4ff7C5T9CbL3+v1+"
    "NE0jmUwSi8WseSmEQEpJMplkbW0NwzBoaGj4x8bzSTQ0NGAYBmtraySTSaSUv5LUFDQMI8fd"
    "2XHMHi8vL/P+/XtisRjLy8ukUikaGxux2+10dnbS3NxcsCd/bBiGRVA142QuWNn5NwlzPD09"
    "zaNHj1hcXLQUmevRaBQhBM+fP8dmszEwMEBnZ2eB8WyY+0U6nc6YPSB70dy0sbHB48ePefv2"
    "LZWVlTQ2NnL27FlaW1spLy9HCEEymWRycpLh4WEWFxdJJBIcPXqU27dvY7fbLb29vb0oisLN"
    "mze5cuUKmqYVtuJ8jI6OMjExQVdXF319fbS0tPDz50/i8TjxeBxd16moqKC9vZ1Lly4xPT3N"
    "s2fP+PbtG+Pj45w/f35X/SqAoihMTEwwOjqKYRgMDAxYAl1dXVRUVNDW1oamaQwNDfHx40fm"
    "5+f58eMHmqZRXV2Nw+HA4/HQ3d3NvXv3iEQiuN3uvf7vFwEpJdPT0zx9+hRd1y0CZija2toA"
    "uH//PpFIhJaWFm7dukVtbS1CCBKJBO/evePly5eMjIzw8OFDy/heDcwKgZSSoqIi6ySEwjK8"
    "ceMGk5OT9Pb2oqq50Tt9+jSvX7/G6XRSWlq6o44dCeyFTCaDy+XC5XIRiUQIhUKMjY0B4HK5"
    "8Pl8XLx40ZLdL+ROC/lKsut4fn6eRCKB2+3G7XazubnJ/Py81d/z/3o3QjkhMDcahpETimxF"
    "Qgh6enro6OiwSiwej2Oz2VBVdduYm5cRc5ytW5qKbTYbZWVlSCmZnZ3d0QvmXHZ9V1dX72jc"
    "lJ+dnUVKSVlZGTabzZq3CDgcDiorK1FVlWAwuKP7dkuq3VwfDAZRVZXKykocDkcuAcMwcLlc"
    "NDU1oSgK4+PjBAKBf+0wCgQCjI+PoygKTU1NuFwuKySqyVTXdfr7+4lGoywtLREKhfj69SsX"
    "Llygvr6+oOz2gqZpLCws8ObNGyYnJxFC4HQ66e/vR9d1K1wFd8KJiQmCwSCRSARd1y1hE4Zh"
    "kE6ntzVaXFxc0EcURUFRFNxuN9euXcPj8eTcCS0C2SS+f/9OOBxmZGSExcVFVlZWrObS0NBA"
    "X1+fdWpmG3/x4gWzs7MIIVhfX6euro7Dhw9z8uRJTpw4QU1NTY5xKwTZjNPpNHa7ne7ubjo6"
    "OkilUkgpuXv3Luvr69TW1nLu3LltPTAyMmJV0JMnTzAMg5KSEuvUzDdeQMAkYbq8vLwcgKKi"
    "IlpbWwmHw4TDYa5fv15gXAhhhevIkSPWGyDbu9sltcy+kOz0aZpGb28vBw4cQEqJpmkFn2ms"
    "pKSEy5cvW2T2+kQqldpX41ZVlZmZGT58+MDKykpBfzAMA7vdzqlTp/B4PDl/vxvE5ubmvk8O"
    "85WzG8zX1H6xbw/8V9jxNPy/8BdGVTdrvKhnqgAAAABJRU5ErkJggg=="
    )

catalog["antenna32_32.ico"] = "antenna32_32_ico"
GetData_antenna32_32_ico   = antenna32_32_ico.GetData
GetImage_antenna32_32_ico  = antenna32_32_ico.GetImage
GetBitmap_antenna32_32_ico = antenna32_32_ico.GetBitmap
GetIcon_antenna32_32_ico   = antenna32_32_ico.GetIcon

#---------------------------------------------------------------------

fountain32_32_active_ico = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABQhJ"
    "REFUWIW9l2uIVGUYx3/vOTM7u7MXV1t1zVuyWqKIlYQUFKaBJWlZSdHFICIwkLDo/kEK9EMf"
    "Ar9EWoGiboFhhUV9kCjKC2V4WYvKFFsv6bo7M+7szsx778OczUXnli098HA47znP+/+f5/Y+"
    "JxRABRUCkgIWCbhNQEpALnoWCrhBwNMCrhNwQoCJbBICFghYLGAwsvOlMGJUlgBY8c7Zgc3t"
    "iTjHfz6y/8U7bnlr6+HfVz8x9/ptHxz644WmcRNnGev49uOtm2Z3THcu2dy25q75hzf/0vfm"
    "hbwXR8/29mxZOnM+0A24ywGEqEwg/tSWHRs6Fi9bFThP5tRJO2ZUSxhrHUfP8WPUjxlHIlaH"
    "sp7chfPEki04YvSd7SZonkC+YDBaus6lHQuAvYC9HCCsQiBx8NMd/TPvWba0UMg3HNmycdPG"
    "J1dsbR7f3vjeI0s2xBqSPa6lbc6ZrgPnNz1w+8ux5pbU6YN7T+x87tG3x99061ypTev5rz/c"
    "3v3Tnk4gD/grEKrkQChgtICZAuZHsZ4kYLyAqQJWrt7X7e9d/+4OAdMFTBDQLmCKgA4Bc6P7"
    "ZDmMajlggf6IfQCYYW5MACIlkqi6pgSQit71w/YWkY0pB1CNwBCJK2IXrflZDSFd8dAPe2/I"
    "zWVB/y2B4R6rizQGxIFEzAsavQ6ARopZ7gAdkXGUivvwzSskYQhMApa99NW+O+uTzbPDeGK8"
    "EGFjKIIwBJS0TisXYI0NwOSlscd6cu7kqR578I2ls4FzlCi9WjwQAtMe339i94SW0VNaw0AY"
    "4zDGY61Da0deWfLShlJZAhuP6ZyJ5QYhna3nXDoAGAX0XC0BATw4kGidmlOefqOR2qG0Q2uL"
    "0Q6jHFJasllFNiNx0oK2DA4YrLJDe1ep8tIEBBBbvv3LhZmCQzuL0o68tGjt8NrilEfmNKne"
    "PDZv8MrhZPHqlSE0BqrEvhqBuE6OniGVRRmLVRarHd44TMGSzUgGLkqEdjhl8dLilAVpccYS"
    "aAdVXF+JAEC9iSfHOm2LX6wdXjtkztDXm8drh7DgjQdz6eqcx1vw3kPp0q3ZA/UurGt0yuK0"
    "xRvPQEaSvajwUvl4185d3Z3rf6RY60ONJ4jsHZAF0rV4oZwH4trHhFXFL0/3FZA5g1MWoZTu"
    "7lz/EfAdoErY+mi98F8I1DknMMpyMVVADmq8diAtXjkL9EYqh9kMZfzw5KuaiGX7gFWO1AWF"
    "leYfcKcsKBtQ7BPD225NYKUkKLM+mOn6ocvn885JB7LofmcEDWe+P0Tx4BkRKUXAA+mjax97"
    "NWaNRRmccnhpwFj+7Hz9C+A3aszyalJqIPGRFjK73+8fNXFyurVw1uu/ju6Jndu/K3vswDaK"
    "8a/ptKsqFYbRegHjBNw457VPjglYGA0cjQKCKoNMzVouBzzFDM8ADe2tk6bNeHjtQxRrO0eN"
    "Xa4WKUdgiASLnl1395hkfeiuufk+YPRIAddCQACNubZ5q0xBkwib2oB51DbEjAiBGLD8ZCo5"
    "ti9dQGtfd+2SdfdT4zE7EgRaZq/57JlCJsf5VJ5svyIXn7YSmPB/EAiB9t60mG6U4VxvjmxW"
    "Im1THFgykgQqxVOYgvFOh1jj8MbiLh2zASPUiCqFoDco9BxxBrxxeOtpkCczwG5G0AOVfs18"
    "7tfPD7VN7pjhYWpCnj6T/uaV54HDlPvNugqpNpY3AS1AawR6kWJz0iMBDvA3rVqYyA2pvmEA"
    "AAAASUVORK5CYII="
    )

catalog["fountain32_32_active.ico"] = "fountain32_32_active_ico"
GetData_fountain32_32_active_ico   = fountain32_32_active_ico.GetData
GetImage_fountain32_32_active_ico  = fountain32_32_active_ico.GetImage
GetBitmap_fountain32_32_active_ico = fountain32_32_active_ico.GetBitmap
GetIcon_fountain32_32_active_ico   = fountain32_32_active_ico.GetIcon

#---------------------------------------------------------------------

fountain32_32_unactive_ico = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAAB0AAAAgCAYAAADud3N8AAAABHNCSVQICAgIfAhkiAAABrZJ"
    "REFUSImdl19sHEcdx78zs7u3t3t3vjvfxX8SJ7WVuHUap4GqhKQQ0ZKWKq1E+xCEeOaBigeQ"
    "qMQzEgKJl0oVUiUeSkFVEajihYIoUVoIrdQ/CS7FqE3i5JI49vls3/+7/b8zPOysb31xSt2R"
    "Tnfe2Z3PfGe+v++OCcEdTQWQBpAHMAqgBKAMwAAgZL/299I/99zO9CazJN3/ZuVrFQA2gFA+"
    "mwFQBXANQA1AHUAXgAeAkyEoBaABGAEwBmD614+/++2O6ZyGQ8Q9S/w9lwWmQ3yzRmr3o1wy"
    "zJTOC031o0xb1AIu/MX0yglnqlzgjLd//qczzwM4D2AVQENOLBiGMjnTIoCpX82/+fTVYuMH"
    "Dywb7/Rn9Ic6vXWTCB9qSgdNm8i5frdlZtOK21XarQ4QCtBskU/WyPsr+83xZjHV/cXvTzwH"
    "oAJgA0AfgE+HlpbIjwpA643R+/eNTpBsCN+pVgSbPgQBAkVToQkfpUr3YmaluuL6LrLprJWf"
    "3CtUVQ9natqV0rq31K4vjwJQ5JhbTRmCiuS33uZrnTxX/jPaeGykPAl6+5YXUg05onptp2tc"
    "Gfcf8UMOvc8aOvWIf7O5DpXqb58YeWYl6OJAK/cKgDYAHwCPx91peQ1poCkA97545I1n6qnu"
    "l3PQ7aPL9F3DDx0Ij334AJ72UpreW1vBbGv0wr0bhU+UUOt2U9StFNzU2VtfXwbwsTTUOoAO"
    "ABcATyolUnn8IQD6zy5+49zH+jsLasg1NRSMIGQesdWimWsurX4ywS0b+SBXN/xUezr4agMe"
    "6uiiIY1TB9CMDSTVblteJvfSQGR5A5GTmaUKYmW47jJuUgiNcUW127anjE6g73KQQHFtCh+A"
    "IwF9uaxtAD2pMNxSRwYqUwCyiGpyAsDcT+f+cNqbMOY9nY05PDAgBCGcQvdCzmwPhmkinRsB"
    "up2Wpact19BsM2dUf/zSsRcAXEXk2I6czBY0VhqrzAAoAJj5/vHfPGd84dABf2Vzw6haC/t9"
    "84bpkE4qoJ7hEa6GYFSACOELTtPCVcCW893R2kl+FsDvANyQYkTCoNugVCrNAMj/7ORfzyxn"
    "uwfEe6vnf7Lw5BtyxpbcFyonqQz9Vl4L35xuRnljSBEMgzLcBiUJpWkAhXWxcTzVDHs/Wjh7"
    "QQIbEhrHoJoYVJHXo7GCMB6PDsPiFnfEgZACkIeKQipgDUTO6yAyhCX3hSagSlK14RGfRhMI"
    "h0E7LS+RgykADGZmNdJsW4gM4MplVRDt99HnHzx30MkoJU8BY4Ig7YWB1ufOf6mrbtpEIAp2"
    "T8IFZKncDUoBMEYIKFW4vJkgKh39hfm/PHpthn+vSkLF7lt9nxI/ABdQAkWMKCwgghBrKwxs"
    "Cd4GjKEkASYAwCgDZSrkEupyCQ07Q+a8pSXlYe/Yb7919YnLGNRgPHCAaP9vy76k2m3Q+EKc"
    "jaEacC4o0wCYcqAAgKGCjChGHsUmq2NgsDjeAkQZa0ngVuztpDQGcjkrP/SD0CzvGfkge2H8"
    "oe4pRfalwXmGhAE8Rh1EJlsD0MIg5kKpzpXf8bU7oHHxBvJGe6Q8Fhq5cvniXPV05eKFc4QQ"
    "sXgPn72I1fvUwmhw5l8PNyRsU6p1MDBMPPlwJ5VJpfEM+wA2yU3/bW0ej4cFzP3jcCtFOIJ1"
    "0psShGFmTX8dwDKiMurIZ/yEojsSaLixRPbGRxX93O2Xu6f0p2Zb1aulTj5dtnN0rDBR1oVQ"
    "Gz98/4k/AriO6OzTwmA//y8sbvHJgcsHLalg7bEPzVeO+gf/tsfMuNwLhXK5d+nUJf0lADcR"
    "HbLu6s7dQh0J7h/rf6VuOKRpt/rO/kxpUxnJi+PtU7W4PwH81PT5NGgM3nIwAHppX/9krk0r"
    "+Yq/0Jg2DyHyQNKVOxplN9CtRALAXj781mzD25gq91KV8Tq7lStljV/Onz+MQdayoed3DY3T"
    "SIE00w2z8UXh+0HZNTbTFnreylrbe3D8JKLXn44ore76JvmsSmMHqwAMRwv3aSGzMy5xNU6F"
    "fbPWtrLGJKJDuIZBhH5uKEn8TQHoSkpNK6W9ggYhpVwQw6d26/Ki9urMW/kEbNfAJDSZvwEA"
    "J1OatI4cmc2s5v0xW+Ppntc3eKvBv3P9EQ+DmtxVqcQtTqQ4wnxExd4q9cniconvvXWf/+S/"
    "e13LLuaL3A9XEb1BXHnv5wIPl4yHqPAb3/3zl15rf3Ttgxub1/X6ocmiyOj20ar5KqJ/huI3"
    "yK6DAdh+wo+PoRlEJ/w9kEfRFw++nn926anrAK4gir91RMm17Wj5Wdv/AB3x8NCi0BnNAAAA"
    "AElFTkSuQmCC"
    )

catalog["fountain32_32_unactive.ico"] = "fountain32_32_unactive_ico"
GetData_fountain32_32_unactive_ico   = fountain32_32_unactive_ico.GetData
GetImage_fountain32_32_unactive_ico  = fountain32_32_unactive_ico.GetImage
GetBitmap_fountain32_32_unactive_ico = fountain32_32_unactive_ico.GetBitmap
GetIcon_fountain32_32_unactive_ico   = fountain32_32_unactive_ico.GetIcon

